//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Preora_DBEntities : DbContext
    {
        public Preora_DBEntities()
            : base("name=Preora_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mst_AccGroup> Mst_AccGroup { get; set; }
        public virtual DbSet<Mst_AccHead> Mst_AccHead { get; set; }
        public virtual DbSet<Mst_Company> Mst_Company { get; set; }
        public virtual DbSet<Mst_ItemGroup> Mst_ItemGroup { get; set; }
        public virtual DbSet<Mst_ItemHead> Mst_ItemHead { get; set; }
        public virtual DbSet<Mst_Shops> Mst_Shops { get; set; }
        public virtual DbSet<Mst_Users> Mst_Users { get; set; }
        public virtual DbSet<tbl_Customers> tbl_Customers { get; set; }
        public virtual DbSet<tbl_Menus> tbl_Menus { get; set; }
        public virtual DbSet<tbl_PRBill_Products> tbl_PRBill_Products { get; set; }
        public virtual DbSet<tbl_PurchaseBill> tbl_PurchaseBill { get; set; }
        public virtual DbSet<tbl_PurchaseBill_Products> tbl_PurchaseBill_Products { get; set; }
        public virtual DbSet<tbl_PurchaseReturnBill> tbl_PurchaseReturnBill { get; set; }
        public virtual DbSet<tbl_Repair> tbl_Repair { get; set; }
        public virtual DbSet<tbl_RepairProduct> tbl_RepairProduct { get; set; }
        public virtual DbSet<tbl_SaleBill> tbl_SaleBill { get; set; }
        public virtual DbSet<tbl_SaleBill_Products> tbl_SaleBill_Products { get; set; }
        public virtual DbSet<tbl_SaleReturnBill> tbl_SaleReturnBill { get; set; }
        public virtual DbSet<tbl_SRBill_Products> tbl_SRBill_Products { get; set; }
        public virtual DbSet<tbl_SubMenu> tbl_SubMenu { get; set; }
        public virtual DbSet<tbl_UserHasMenus> tbl_UserHasMenus { get; set; }
    }
}
