//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Users
    {
        public int id { get; set; }
        public string Uname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string rolename { get; set; }
        public Nullable<int> shopid { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
