//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_AccHead
    {
        public int id { get; set; }
        public Nullable<int> AccGroupid { get; set; }
        public string AccName { get; set; }
        public string AccCode { get; set; }
        public Nullable<decimal> OpeningAmount { get; set; }
        public string RegType { get; set; }
        public string AccGST { get; set; }
        public string AccPAN { get; set; }
        public string AccContactPerson { get; set; }
        public string AccArea { get; set; }
        public string AccAddress { get; set; }
        public string AccCity { get; set; }
        public string AccPincode { get; set; }
        public string AccPhone { get; set; }
        public string AccEmail { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
