//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaleBill_Products
    {
        public int id { get; set; }
        public Nullable<int> salebillid { get; set; }
        public Nullable<int> itemheadid_s { get; set; }
        public Nullable<decimal> itemrate_s { get; set; }
        public Nullable<long> itemqty_s { get; set; }
        public Nullable<decimal> gross_amt_s { get; set; }
        public Nullable<decimal> discamount_s { get; set; }
        public Nullable<decimal> sgstamt_s { get; set; }
        public Nullable<decimal> cgstamt_s { get; set; }
        public Nullable<decimal> igstamt_s { get; set; }
        public string HSNSAC_s { get; set; }
        public Nullable<decimal> finalprice_s { get; set; }
    }
}
