//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaleBill
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string s_entrycode { get; set; }
        public string custname { get; set; }
        public string custphone { get; set; }
        public Nullable<System.DateTime> billdate_s { get; set; }
        public string invoiceno { get; set; }
        public Nullable<decimal> GrossAmt_s { get; set; }
        public Nullable<decimal> Discount_s { get; set; }
        public Nullable<decimal> AdditionalDisc_s { get; set; }
        public Nullable<decimal> SGST_s { get; set; }
        public Nullable<decimal> CGST_s { get; set; }
        public Nullable<decimal> IGST_s { get; set; }
        public Nullable<decimal> FinalAmt_s { get; set; }
        public Nullable<decimal> PaidAmt_s { get; set; }
        public Nullable<decimal> BalanceAmt_s { get; set; }
        public string paymode { get; set; }
    }
}
