//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SRBill_Products
    {
        public int id { get; set; }
        public Nullable<int> SR_salebillid { get; set; }
        public Nullable<int> SR_itemheadid { get; set; }
        public Nullable<decimal> SR_itemrate { get; set; }
        public Nullable<long> SR_itemqty { get; set; }
        public Nullable<decimal> SR_gross_amt { get; set; }
        public Nullable<decimal> SR_discamount { get; set; }
        public Nullable<decimal> SR_sgstamt { get; set; }
        public Nullable<decimal> SR_cgstamt { get; set; }
        public Nullable<decimal> SR_igstamt { get; set; }
        public string SR_HSNSAC { get; set; }
        public Nullable<decimal> SR_finalprice { get; set; }
    }
}
