//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaleReturnBill
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string SR_entrycode { get; set; }
        public string SR_custname { get; set; }
        public Nullable<System.DateTime> SR_billdate { get; set; }
        public Nullable<System.DateTime> SR_duedate { get; set; }
        public string SR_invoicetype { get; set; }
        public string SR_invoiceno { get; set; }
        public Nullable<decimal> SR_GrossAmt { get; set; }
        public Nullable<decimal> SR_Discount { get; set; }
        public Nullable<decimal> SR_AdditionalDisc { get; set; }
        public Nullable<decimal> SR_SGST { get; set; }
        public Nullable<decimal> SR_CGST { get; set; }
        public Nullable<decimal> SR_IGST { get; set; }
        public Nullable<decimal> SR_othercharge { get; set; }
        public Nullable<decimal> SR_FinalAmt { get; set; }
        public Nullable<decimal> SR_PaidAmt { get; set; }
        public Nullable<decimal> SR_BalanceAmt { get; set; }
        public string SR_paymode { get; set; }
    }
}
