//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseReturnBill
    {
        public int id { get; set; }
        public string PR_code { get; set; }
        public Nullable<int> PR_suppid { get; set; }
        public Nullable<System.DateTime> PR_billdate { get; set; }
        public Nullable<System.DateTime> PR_duedate { get; set; }
        public string PR_invoiceno { get; set; }
        public Nullable<decimal> PR_GrossAmt { get; set; }
        public Nullable<decimal> PR_Discount { get; set; }
        public Nullable<decimal> PR_AdditionalDisc { get; set; }
        public Nullable<decimal> PR_S_GST { get; set; }
        public Nullable<decimal> PR_C_GST { get; set; }
        public Nullable<decimal> PR_I_GST { get; set; }
        public Nullable<decimal> PR_LoadingCharge { get; set; }
        public Nullable<decimal> PR_FinalAmt { get; set; }
        public Nullable<decimal> PR_PaidAmt { get; set; }
        public Nullable<decimal> PR_BalanceAmt { get; set; }
        public string PR_pay_mode { get; set; }
    }
}
