//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PRBill_Products
    {
        public int id { get; set; }
        public Nullable<int> PR_purchasebill_id { get; set; }
        public Nullable<int> PR_itemhead_id { get; set; }
        public Nullable<decimal> PR_item_rate { get; set; }
        public Nullable<long> PR_item_qty { get; set; }
        public Nullable<decimal> PR_gross_amt { get; set; }
        public Nullable<decimal> PR_disc_amt { get; set; }
        public Nullable<decimal> PR_sgst_amt { get; set; }
        public Nullable<decimal> PR_cgst_amt { get; set; }
        public Nullable<decimal> PR_igst_amt { get; set; }
        public string PR_HSN_SAC { get; set; }
        public Nullable<decimal> PR_finalprod_amt { get; set; }
    }
}
