//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customers
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string mobileno { get; set; }
        public string whatsapno { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> AnnDate { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string NameNo { get; set; }
    }
}
