//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preora.dbcon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseBill_Products
    {
        public int id { get; set; }
        public Nullable<int> purchasebill_id { get; set; }
        public Nullable<int> itemhead_id { get; set; }
        public Nullable<decimal> item_rate { get; set; }
        public Nullable<long> item_qty { get; set; }
        public Nullable<decimal> gross_amt { get; set; }
        public Nullable<decimal> disc_amt { get; set; }
        public Nullable<decimal> sgst_amt { get; set; }
        public Nullable<decimal> cgst_amt { get; set; }
        public Nullable<decimal> igst_amt { get; set; }
        public string HSN_SAC { get; set; }
        public Nullable<decimal> finalprod_amt { get; set; }
    }
}
